run:
  name: "regional-variation"
  disable_progressbar: true

foresight: "myopic"

scenario:
  simpl:
    - "60"
  clusters:
    - "20"
  ll:
    - "c1.1"
  opts:
    - ""
  sector_opts:
    - "1000SEG-T-H-B-I-A-Co2L0.45-EXPORT2-LIM+SOUTH+5"
    - "1000SEG-T-H-B-I-A-Co2L0.45-EXPORT2-LIM+SOUTH+10"
    - "1000SEG-T-H-B-I-A-Co2L0.45-EXPORT2-LIM+SOUTH+20"
    - "1000SEG-T-H-B-I-A-Co2L0.45-EXPORT2-LIM+SOUTH+30"
    - "1000SEG-T-H-B-I-A-Co2L0.45-EXPORT2-LIM+SOUTH+40"
    - "1000SEG-T-H-B-I-A-Co2L0.45-EXPORT2-LIM+SOUTH+50"
    - "1000SEG-T-H-B-I-A-Co2L0.45-EXPORT2-LIM+SOUTH+60"
    - "1000SEG-T-H-B-I-A-Co2L0.45-EXPORT2-LIM+SOUTH+70"
    - "1000SEG-T-H-B-I-A-Co2L0.45-EXPORT2-LIM+SOUTH+80"
  planning_horizons:
    - 2030

param_sweep_num_nets: 50
param_sweep:
  onwind_cost:
    carrier: "onwind"
    attr: "c" # Capital cost
    range: [0.8, 1.2]
  offwind-fixed_cost:
    carrier: "offwindfixed"
    attr: "c" # Capital cost
    range: [0.8, 1.2]
  offwind-float_cost:
    carrier: "offwindfloat"
    attr: "c" # Capital cost
    range: [0.8, 1.2]
  SMR_cost:
    carrier: "SMR CC"
    attr: "c" # Capital cost
    range: [0.8, 1.2]
  gas_cost:
    carrier: "gas"
    attr: "m" # Marginal cost
    range: [0.8, 1.2]
  sequestration_cost:
    carrier: "co2 stored"
    attr: "c" # Capital cost: sequestration is modelled as store
    range: [0.8, 1.2]
  electrolysis_cost:
    carrier: "H2 Electrolysis"
    attr: "c" # Capital cost
    range: [0.8, 1.2]
  electrolysis_efficiency:
    carrier: "H2 Electrolysis"
    attr: "f" # Efficiency
    range: [0.935, 1.065] # Given a HHV efficiency of 77%, this corresponds to a range of 72%-82%.
  export_capital_cost:
    carrier: "H2 export"
    attr: "c" # Capital cost
    range: [0.8, 1.2]
  export_marginal_cost:
    carrier: "H2 export"
    attr: "m" # Marginal cost
    range: [0.8, 1.2]


countries: ["NO", "SE", "FI", "NL", "DE", "DK", "GB"]

focus_weights:
  "NO": 0.69
  "SE": 0.2
  "FI": 0.1
  "NL": 0.0025
  "DE": 0.0025
  "DK": 0.0025
  "GB": 0.0025

electricity:
  # Only select powerplants phased out after 2022. Note that this is
  # only relevant for the initial network; for the 2030 planning
  # horizon network (at add_brownfield) powerplants that are
  # decommissioned by 2030 are removed anyway.
  powerplants_filter: (DateOut >= 2022 or DateOut != DateOut)

  estimate_renewable_capacities:
    year: 2022

atlite:
  nprocesses: 8
  cutouts:
    base:
      module: era5

sector:
  norwegian_hydrogen_exports: true
  gas_network: true
  H2_retrofit: false
  H2_network: false
  co2_spatial: false
  co2_sequestration_lifetime: .inf
  co2_sequestration_cost: 28.7
  co2network: false
  SMR: false
  SMR_cc: false # Scenario B: NO SMR
  methanation: false
  dac: false
  ammonia: "regional"
  fischer_tropsch: false
  biomass_spatial: true
  conventional_generation:
    OCGT: gas
    nuclear: uranium

existing_capacities:
  conventional_carriers:
    - lignite
    - coal
    - oil
    - uranium
    - gas

costs:
  year: 2030
  capital_cost:
    # From NVE, we have that floating offwind (excluding connection
    # costs) costs 46000 NOK / kWel in 2021 NOK.
    # With a conversion rate for 2021 of 0.0984, this is 4526 EUR_2021.
    # Using Eurostat HICP rates we find that inflation 2015-2021 was 8.82%,
    # Making for a cost of 4160 EUR_2015
    offwind-float: 4160
    # From NVE, we get a bottom-fixed offshore wind investment cost of
    # 25500 NOK / kWel in 2021 NOK. Similar to the above, this is 2509
    # EUR_2021, and thus 2305 EUR_2015.
    offwind: 2305
    # From NVE, we get an onshore wind investment cost of 12340 NOK / kWel.
    # With the same calculation as above, this is 1214 EUR_2021,
    # equivalent to 1116 EUR_2015
    onwind: 1116
    electrolysis: 337

clustering:
  simplify_network:
    remove_stubs: ["GB", "DE", "NL", "DK", "SE", "FI"]

solving:
  solver_options:
    gurobi-default:
      threads: 1

compression:
  enable: true
  options:
    zlib: true
    complevel: 3
    least_significant_digit: 3

wind_bias_correction:
  corrector_year: 2013
  num_near_wind_parks: 10
  num_parallel_processes: 48

plotting:
  map:
    # Whole region:
    # boundaries: [0, 25, 45, 71]
    # Just Norway:
    boundaries: [0, 26, 57, 72]
  eu_node_location:
    x: 0.
    y: 60.
  tech_colors:
    H2 export: "#f081dc"
