# SPDX-FileCopyrightText: 2024 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC0-1.0


remote:
  ssh: ""
  path: ""

run:
  name: "eu-hydrogen"
  disable_progressbar: true
  shared_resources: false
  shared_cutouts: true

foresight: perfect

scenario:
  simpl:
  - ''
  ll:
  - c1.2
  clusters:
  - 35
  opts:
  - ''
  sector_opts:
  - 1p5-30seg-seq200
  - 1p5-30seg-seq500
  - 1p5-30seg-seq800
  - 1p7-30seg-seq200
  - 1p7-30seg-seq500
  - 1p7-30seg-seq800
  - 2p0-30seg-seq200
  - 2p0-30seg-seq500
  - 2p0-30seg-seq800
  planning_horizons:
  - 2025
  - 2030
  - 2040
  - 2050

near_opt:
  num_parallel: 6
  slacks: [0.02, 0.05, 0.1]
  weights:
    # static:
    #   Link:
    #     p_nom:
    #       "H2 Electrolysis": 1
    #       "SMR": 1
    #       "SMR CC": 1
    varying:
      Link:
        p:
          "H2 Electrolysis": 1
          "SMR": 1
          "SMR CC": 1

# Use full set of countries (default)
# countries: ["AL", "AT", "BA", "BE", "BG", "CH", "CZ", "DE", "DK", "EE", "ES", "FI", "FR", "GB", "GR", "HR", "HU", "IE", "IT", "LT", "LU", "LV", "ME", "MK", "NL", "NO", "PL", "PT", "RO", "RS", "SE", "SI", "SK"]


# EU-27, exclude Cyprus, Luxembourg, Malta (too small), plus Norway, UK, Switzerland
countries:
- "BE"
- "BG"
- "CZ"
- "DK"
- "DE"
- "EE"
- "IE"
- "GR"
- "ES"
- "FR"
- "HR"
- "IT"
- "LV"
- "LT"
- "HU"
- "NL"
- "AT"
- "PL"
- "PT"
- "RO"
- "SI"
- "SK"
- "FI"
- "SE"
- "NO"
- "GB"
- "CH" 

# Use segmentation for time aggregation
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: "left"

# Also retrieve IRENA data on existing renewable generation
enable:
  retrieve_irena: true

co2_budget:
  # For perfect foresight: (from technological learning paper)
  # update of IPCC 6th AR compared to the 1.5SR. (discussed here: https://twitter.com/JoeriRogelj/status/1424743828339167233)
  1p5: 34.2 # 25.7 # Budget in Gt CO2 for 1.5 for Europe, global 420 Gt, assuming per capita share
  1p6: 43.259666 # 35  # Budget in Gt CO2 for 1.6 for Europe, global 580 Gt
  1p7: 51.4 # 45  # Budget in Gt CO2 for 1.7 for Europe, global 800 Gt
  2p0: 69.778 # 73.9 # Budget in Gt CO2 for 2 for Europe, global 1170 Gt


# Use default configuration for which generators to include
electricity:
  extendable_carriers:
    # Extendable renewables are created here, but conventional
    # extendable generation is handled in sector config section.
    Generator: [solar, onwind, offwind-ac, offwind-dc]
    StorageUnit: []
    Store: []
    Link: []

  # Don't include powerplants that are already decommissioned.
  powerplants_filter: (DateOut >= 2022 or DateOut != DateOut)

  # Conventional carriers are all added in prepare_sector_network and add_existing_baseyear
  conventional_carriers: []
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]

  estimate_renewable_capacities:
    enable: false
    
# In prepare_sector_network, keep the following existing generators. Note: _do not_ include nuclear as this is added back with historical capacities as a link in sector-coupled network.
pypsa_eur:
  Bus:
  - AC
  Link:
  - DC
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - solar
  - ror
  StorageUnit:
  - PHS
  - hydro
  Store: []

# Use only ERA5 cutout
atlite:
  default_cutout: europe-2013-era5
  nprocesses: 4
  show_progress: false
  cutouts:
    europe-2013-era5:
      module: era5 # in priority order
      x: [-12., 42.]
      y: [33., 72]
      dx: 0.3
      dy: 0.3
      time: ['2013', '2013']

# Switch to ERA5 for solar; apply recommended correction factor (https://github.com/PyPSA/pypsa-eur/pull/304)
renewable:
  solar:
    cutout: europe-2013-era5
    correction_factor: 0.854337

# Default:
energy:
  energy_totals_year: 2011
  base_emissions_year: 1990
  eurostat_report_year: 2016
  emissions: CO2

sector:
  # Default transport shares:
  land_transport_fuel_cell_share:
    2020: 0
    2025: 0
    2030: 0
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  land_transport_electric_share:
    2020: 0
    2025: 0.15
    2030: 0.3
    2035: 0.45
    2040: 0.7
    2045: 0.85
    2050: 1
  land_transport_ice_share:
    2020: 1
    2025: 0.85
    2030: 0.7
    2035: 0.55
    2040: 0.3
    2045: 0.15
    2050: 0
  # Default agriculture fuel shares:
  agriculture_machinery_electric_share: 0
  agriculture_machinery_oil_share: 1
  agriculture_machinery_fuel_efficiency: 0.7
  agriculture_machinery_electric_efficiency: 0.3
  # Default shipping options:
  shipping_hydrogen_liquefaction: false
  shipping_hydrogen_share:
    2020: 0
    2025: 0
    2030: 0
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  shipping_methanol_share:
    2020: 0
    2025: 0.15
    2030: 0.3
    2035: 0.5
    2040: 0.7
    2045: 0.85
    2050: 1
  shipping_oil_share:
    2020: 1
    2025: 0.85
    2030: 0.7
    2035: 0.5
    2040: 0.3
    2045: 0.15
    2050: 0
  # Default aviation demand:
  aviation_demand_factor: 1.
  # Default demand for high value petro-chemicals (HVC):
  HVC_demand_factor: 1.
  # Do allow heat venting to prevent potential infeasibility
  central_heat_vent: true
  # Allow both grey and blue hydrogen
  SMR: true
  SMR_cc: true
  # No regional oil, methanol demand
  regional_methanol_demand: false
  regional_oil_demand: false
  # Assume 20 EUR / tCO2 sequestered. NB: might need to update this.
  co2_sequestration_cost: 20
  # Don't resolve CO2 spatially
  co2_spatial: false
  # However, don't allow transport of CO2
  co2network: false
  # Don't include ammonia sector
  ammonia: false
  # Turn off minimum part load for now (could lead to infeasibility)
  min_part_load_fischer_tropsch: 0.
  min_part_load_methanolisation: 0.
  min_part_load_methanation: 0.
  # Don't use waste heat from conversion processes
  use_fischer_tropsch_waste_heat: false
  use_haber_bosch_waste_heat: false
  use_methanolisation_waste_heat: false
  use_methanation_waste_heat: false
  use_fuel_cell_waste_heat: false
  use_electrolysis_waste_heat: false
  # Cluster heat buses
  cluster_heat_buses: true
  # Don't model distribution grid
  electricity_distribution_grid: false
  electricity_distribution_grid_cost_factor: 1.0
  electricity_grid_connection: true
  # Don't spatially resolve gas; only hydrogen
  H2_network: true
  gas_network: false
  # Don't allow retrofitting
  H2_retrofit: false
  # Don't spatially resolve biomass
  biomass_spatial: false
  biomass_transport: false
  # Don't split links to model efficiency losses
  transmission_efficiency:
  # Allow expansion of gas generations, nuclear
  conventional_generation:
    OCGT: "gas"
    nuclear: "uranium"
  # Growth limits configuration
  limit_max_growth:
    enable: false
    # allowing 30% larger than max historic growth
    factor: 1.3
    max_growth:  # unit GW
      # onshore max grow so far 16 GW in Europe https://www.iea.org/reports/renewables-2020/wind
      onwind: 16
      # solar max grow so far 28 GW in Europe https://www.iea.org/reports/renewables-2020/solar-pv
      solar: 28
      # offshore max grow so far 3.5 GW in Europe https://windeurope.org/about-wind/statistics/offshore/european-offshore-wind-industry-key-trends-statistics-2019/
      offwind-ac: 3.5
      offwind-dc: 3.5
      # Hard assumption: 10 GW per year for electrolysis
      "H2 Electrolysis": 3
    # The above absolute growth is in addition to the below relative
    # growth, which is per investment period.
    max_relative_growth:
      onwind: 2
      solar: 2
      offwind-ac: 2
      offwind-dc: 2
      "H2 Electrolysis": 2

industry:
  # Default assumtions for metal industry energy carrier use:
  St_primary_fraction:
    2020: 0.6
    2025: 0.55
    2030: 0.5
    2035: 0.45
    2040: 0.4
    2045: 0.35
    2050: 0.3
  DRI_fraction:
    2020: 0
    2025: 0
    2030: 0.05
    2035: 0.2
    2040: 0.4
    2045: 0.7
    2050: 1
  H2_DRI: 1.7
  elec_DRI: 0.322
  Al_primary_fraction:
    2020: 0.4
    2025: 0.375
    2030: 0.35
    2035: 0.325
    2040: 0.3
    2045: 0.25
    2050: 0.2

costs:
  # Technology data repository version
  version: v0.6.2
  # Default social discount rate of 2%
  social_discountrate: 0.02

# Default solving options
solving:
  options:
    # Don't use noisy costs; makes solving time inconsistent
    noisy_costs: false
    # Assign all duals to solution
    assign_all_duals: false
    # Use direct solver API
    io_api: "direct"
    # Don't attempt computing and print infeasibilities
    print_infeasibilities: false

  # Use default gurobi configuration
  solver:
    name: gurobi
    options: gurobi-default

  solver_options:
    gurobi-default:
      threads: 4
      method: 2 # barrier
      crossover: 0
      BarConvTol: 1.e-6
      Seed: 123
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200
      BarHomogeneous: 1

  mem: 70000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2
  walltime: "12:00:00"

compression:
  enable: true
  options:
    zlib: true
    complevel: 1
    least_significant_digit: 3

# Default plotting configuration
plotting:
  map:
    boundaries:
    color_geomap:
      ocean: white
      land: white
  projection:
    name: "LambertConformal"
    central_longitude: 10.
    central_latitude: 50.
    standard_parallels: [35, 65]
  eu_node_location:
    x: -5.5
    y: 46.
  costs_max: 1000
  costs_threshold: 1
  energy_max: 20000
  energy_min: -20000
  energy_threshold: 50.

  nice_names:
    OCGT: "Open-Cycle Gas"
    CCGT: "Combined-Cycle Gas"
    offwind-ac: "Offshore Wind (AC)"
    offwind-dc: "Offshore Wind (DC)"
    onwind: "Onshore Wind"
    solar: "Solar"
    PHS: "Pumped Hydro Storage"
    hydro: "Reservoir & Dam"
    battery: "Battery Storage"
    H2: "Hydrogen Storage"
    lines: "Transmission Lines"
    ror: "Run of River"
    load: "Load Shedding"
    ac: "AC"
    dc: "DC"
