

run:
    name: "hydrogen-exports"
    disable_progressbar: true

foresight: "myopic"

scenario:
    simpl:
    - ""
    clusters:
    - "45"
    # - "30"
    ll:
    - "c1.1"
    opts:
    - ""
    sector_opts:
    # - "1500SEG-T-H-B-I-A-Co2L0.5-EXPORT10"
    # - "1500SEG-T-H-B-I-A-Co2L0.4-EXPORT10"
    # - "1500SEG-T-H-B-I-A-Co2L0.3-EXPORT10"
    # - "1500SEG-T-H-B-I-A-Co2L0.2-EXPORT10"
    # - "1500SEG-T-H-B-I-A-Co2L0.5-EXPORT10north"
    # - "1500SEG-T-H-B-I-A-Co2L0.4-EXPORT10north"
    # - "1500SEG-T-H-B-I-A-Co2L0.3-EXPORT10north"
    # - "1500SEG-T-H-B-I-A-Co2L0.2-EXPORT10north"
    - "100SEG-T-H-B-I-A-Co2L0.5-EXPORT10"
    - "100SEG-T-H-B-I-A-Co2L0.47-EXPORT10"
    - "100SEG-T-H-B-I-A-Co2L0.43-EXPORT10"
    - "100SEG-T-H-B-I-A-Co2L0.4-EXPORT10"
    - "100SEG-T-H-B-I-A-Co2L0.5-EXPORT10north"
    - "100SEG-T-H-B-I-A-Co2L0.47-EXPORT10north"
    - "100SEG-T-H-B-I-A-Co2L0.43-EXPORT10north"
    - "100SEG-T-H-B-I-A-Co2L0.4-EXPORT10north"
    planning_horizons:
    - 2030

countries: ["NO", "SE", "NL", "DE", "DK"]

focus_weights:
    "NO": 0.69
    "SE": 0.3
    "NL": 0.0033
    "DE": 0.0033
    "DK": 0.0033

electricity:
    # Only select powerplants phased out after 2022. Note that this is
    # only relevant for the initial network; for the 2030 planning
    # horizon network (at add_brownfield) powerplants that are
    # decommissioned by 2030 are removed anyway.
    powerplants_filter: (DateOut >= 2022 or DateOut != DateOut)

    estimate_renewable_capacities:
        year: 2022

atlite:
    cutouts:
        base:
            module: era5

costs:
    year: 2030

sector:
    regional_co2_sequestration_potential:
        enable: true
    gas_network: true
    H2_retrofit: true
    co2_spatial: false
    co2network: false
    methanation: false
    dac: false
    ammonia: true
    fischer_tropsch: false
    biomass_spatial: true
    conventional_generation:
        OCGT: gas

existing_capacities:
    conventional_carriers:
    - lignite
    - coal
    - oil
    - uranium

clustering:
    simplify_network:
        algorithm: "hac"
        feature: "onwind-time"
    cluster_network:
        algorithm: "hac"
        feature: "onwind-time"

solving:
    solver_options:
        gurobi-default:
            threads: 2
        
plotting:
    map:
        boundaries: [0, 25, 45, 71]
    eu_node_location:
        x: 0.
        y: 60.
